### ISSUE TITLE
Missing `type` field for associative array in Update Metadata Template

### ISSUE THREAD

**Issue by yusuf-musleh** [box/box-openapi#100]
Hello,

It seems like the `type` field is missing from the associative array `data` in following:

https://github.com/box/box-openapi/blob/46deb09dea7038247db0dd089007bf9e74e7415c/content/attributes/metadata_template_operation.yml#L36

**Comment by cbetta** [comment]
Thank you @yusuf-musleh. I think `type: object` is optional in this case, but I've added the line and made sure we're explicit in all other cases where we have an associative array.
