### ISSUE TITLE
Small typo in Create Comment endpoint description

### ISSUE THREAD

**Issue by yusuf-musleh** [box/box-openapi#101]
Hello,

Found a small typo in the description of the `Create Comment` endpoint, just thought I'd flag it. 😃 

https://github.com/box/box-openapi/blob/fcdfed815bd29ceda5b316f254bfd47e055c8d6c/content/paths/comments__post_comments.yml#L12

**Comment by cbetta** [comment]
Thank you @yusuf-musleh, fixed!
