### ISSUE TITLE
Missing `context_info` field in `Client Error`?

### ISSUE THREAD

**Issue by yusuf-musleh** [box/box-openapi#102]
Hello,

I was making a request to the `Create Folder` endpoint with different payloads, some with missing required params to see how the response would look like, I get the following:

```
{
  "type": "error",
  "status": 400,
  "code": "bad_request",
  "context_info": {
    "errors": [
      {
        "reason": "missing_parameter",
        "name": "parent",
        "message": "'parent' is required"
      },
      {
        "reason": "missing_parameter",
        "name": "name",
        "message": "'name' is required"
      }
    ]
  },
  "help_url": "http://developers.box.com/docs/#errors",
  "message": "Bad Request",
  "request_id": "cksn44gg20atvj21"
}
```
I noticed the `context_info` field in the response however I couldn't find it in the spec for `ClientError`, was that intended or is it just missing from the spec?

https://github.com/box/box-openapi/blob/3b6cb61ad54daed42554855101ad7d88cbb69441/content/errors/client_error.yml#L11-L69

**Comment by cbetta** [comment]
Hi @yusuf-musleh, you are 100% right, our API spec is missing this detail. We are currently still reviewing all the errors our API returns so that we can retroactively update the client error object with the details. As this is still a work in progress, this info is currently missing from the spec.

**Comment by yusuf-musleh** [comment]
@cbetta Thanks for clearing that up for me. Where can I find the spec that reflects the current state of the released API? I noticed the one I downloaded from the README in the default branch gets updated quite frequently and I assume it might not be entirely in sync with the currently released API?

**Comment by Smartoneinok** [comment]
context_info was added.... https://developer.box.com/reference/resources/client-error/
That said... every error is different. We have some listed at https://developer.box.com/guides/api-calls/permissions-and-errors/common-errors/
