### ISSUE TITLE
`notification_email` object field in User returns empty list when not set

### ISSUE THREAD

**Issue by yusuf-musleh** [box/box-openapi#103]
Hello,

When I make requests to `Get Current User` and `Get User` and didn't have the a notification email set for that user, I got back a empty list, rather than `{}` or  `null`:
```
{
  "type": "user",
  "id": "***********",
  "name": "Name",
  "login": "example@email.com",
  "created_at": "2020-06-18T10:25:18-07:00",
  "modified_at": "2020-06-24T16:38:41-07:00",
  "language": "en",
  "timezone": "America/Los_Angeles",
  "space_amount": 10737418240,
  "space_used": 40595,
  "max_upload_size": 2147483648,
  "status": "active",
  "job_title": "",
  "phone": "222222222",
  "address": "",
  "avatar_url": "https://app.box.com/api/avatar/large/***********",
  "notification_email": []
}
```
However when I set a notification email for that user, I got back an object as expected from the spec:
```
{
  "type": "user",
  "id": "***********",
  "name": "Name",
  "login": "example@email.com",
  "created_at": "2020-06-18T10:25:18-07:00",
  "modified_at": "2020-06-24T20:37:24-07:00",
  "language": "en",
  "timezone": "America/Los_Angeles",
  "space_amount": 10737418240,
  "space_used": 40595,
  "max_upload_size": 2147483648,
  "status": "active",
  "job_title": "",
  "phone": "222222222",
  "address": "",
  "avatar_url": "https://app.box.com/api/avatar/large/***********",
  "notification_email": {
    "email": "notifications@email.com",
    "is_confirmed": true
  }
}
```
Just thought I'd flag this, and was wondering what usually happens in cases like these? Does the specification get updated or does the API itself get updated since they're different types depending on the case?

https://github.com/box/box-openapi/blob/fcdfed815bd29ceda5b316f254bfd47e055c8d6c/content/responses/user.yml#L134-L136

**Comment by cbetta** [comment]
Hi @yusuf-musleh, thank you for reporting this. This seems to be a bug in our API, I've reported it.

**Comment by Smartoneinok** [comment]
Hello - looks like this issue was looked into... The eng team this is expected as [] means null.
