### ISSUE TITLE
Data type field missing for some parameters

### ISSUE THREAD

**Issue by Band-Aid** [box/box-openapi#106]
## Description of the issue

I am ingesting the openapi file in to my strictly typed project and noticed box openapi does not include the data type for each parameter.

## Current content

no data types

## Expected content

please add data types for each parameter

**Comment by box-devrel** [comment]
@Band-Aid we have linters in place for this and they definitely should be in place. Can you give me an example please?

**Comment by cbetta** [comment]
@Band-Aid we have linters in place for this and they definitely should be in place. Can you give me an example please?

**Comment by Band-Aid** [comment]
Ah, sorry I reacted too soon.
My parser wasn't picking up the data type correctly.
