### ISSUE TITLE
The Open API Specification files are outdated

### ISSUE THREAD

**Issue by ramanpalikala** [box/box-openapi#14]
The Open API Specification files that Box provides at the Github URL
    https://github.com/box/box-openapi/tree/master/v2.0
are outdated.

**The new Open API Specification files should be made available** at Github in some other branch
so that it will be in sync with the Box API that Box exposes to public.

**Comment by ramanpalikala** [comment]
Could anyone please look into it?
My advanced thanks..

**Comment by cbetta** [comment]
@ramanpalikala work on this has started. I will keep you posted.
