### ISSUE TITLE
Event Resource - Source - Returns File Resource rather than Event Source

### ISSUE THREAD

**Issue by mitquinn** [box/box-openapi#146]
## Description of the issue
So the documentation says the Event Resource source field will be a User | Event source resource. But it seems like its never returning an Event source, but rather its returning a User|File|Folder. 

![image](https://user-images.githubusercontent.com/9064425/113249738-390b0680-928d-11eb-9295-89089d2ac6dd.png)

I am expecting an object with this values: https://developer.box.com/reference/resources/event-source/

But what I am seeing looks like a File Resource. (which is leading me to believe this would be a Folder resource as well)

`array(23) {
  'type' =>
  string(4) "file"
  'id' =>
  string(12) "789214426768"
  'file_version' =>
  array(3) {
    'type' =>
    string(12) "file_version"
    'id' =>
    string(12) "843545438368"
    'sha1' =>
    string(40) "cfdbc6607b7edab16f9efbd08d8cd15a9dfe48b0"
  }
  'sequence_id' =>
  string(1) "0"
  'etag' =>
  string(1) "0"
  'sha1' =>
  string(40) "cfdbc6607b7edab16f9efbd08d8cd15a9dfe48b0"
  'name' =>
  string(5) "Roger"
  'description' =>
  string(0) ""
  'size' =>
  int(12)
  'path_collection' =>
  array(2) {
    'total_count' =>
    int(1)
    'entries' =>
    array(1) {
      [0] =>
      array(5) {
        ...
      }
    }
  }
  'created_at' =>
  string(25) "2021-03-19T17:44:12-07:00"
  'modified_at' =>
  string(25) "2021-03-19T17:44:12-07:00"
  'trashed_at' =>
  NULL
  'purged_at' =>
  NULL
  'content_created_at' =>
  string(25) "2021-03-19T17:44:11-07:00"
  'content_modified_at' =>
  string(25) "2021-03-19T17:44:11-07:00"
  'created_by' =>
  array(4) {
    'type' =>
    string(4) "user"
    'id' =>
    string(11) "14742537355"
    'name' =>
    string(15) "ComposerPackage"
    'login' =>
    string(51) "Removed.com"
  }
  'modified_by' =>
  array(4) {
    'type' =>
    string(4) "user"
    'id' =>
    string(11) "14742537355"
    'name' =>
    string(15) "ComposerPackage"
    'login' =>
    string(51) "Removed@boxdevedition.com"
  }
  'owned_by' =>
  array(4) {
    'type' =>
    string(4) "user"
    'id' =>
    string(11) "14742537355"
    'name' =>
    string(15) "ComposerPackage"
    'login' =>
    string(51) "Removed@boxdevedition.com"
  }
  'shared_link' =>
  NULL
  'parent' =>
  array(5) {
    'type' =>
    string(6) "folder"
    'id' =>
    string(1) "0"
    'sequence_id' =>
    NULL
    'etag' =>
    NULL
    'name' =>
    string(9) "All Files"
  }
  'item_status' =>
  string(6) "active"
  'synced' =>
  bool(true)
}`

## Current content
Event > source - returns User|Event source

## Expected content
Event > source - returns User|File|Folder

**Comment by mitquinn** [comment]
See #147 

I think this is the correct fix. But it needs to be verified by someone from Box.

**Comment by Smartoneinok** [comment]
This has been fixed.
