### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by MikeRalphson** [box/box-openapi#2]
LICENSE and README state Apache 2.0 but OpenAPI definitions say MIT (with a link to http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT) - linking directly to grunt's LICENSE seems to be a (mis)feature of APIMatic's API tooling.

**Comment by KarthikShanmugasundaram** [comment]
@MikeRalphson It is resolved. Thanks for pointing it out.
