### ISSUE TITLE
$ref where there shouldn't be a $ref

### ISSUE THREAD

**Issue by philsturgeon** [box/box-openapi#210]
## Description of the issue

Hey folks,  I'm working with the OAI, looking for great projects using OpenAPI, and when I was checking out yours I noticed some invalid stuff going on. There are only a few specific places that a `$ref` is allowed, but unfortunately you've got them in places that are not valid. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67381/152642520-59d6bb1f-c4a9-4f4c-8238-78dfdf1992c3.png">

This is just the output of popping https://raw.githubusercontent.com/box/box-openapi/main/content/openapi.yml into editor.swagger.io if you'd like to recreate it. 

Swagger Editor isn't alone in struggling here, Stoplight Elements also will not load. https://elements-demo.stoplight.io/?spec=https://raw.githubusercontent.com/box/box-openapi/main/content/openapi.yml

I took a swing at fixing it by moving the contents of paths.yml and schemas.yml into the main openapi.yml, which helped a bit, but now I'm noticing more things which are technically not valid. 

For example, inside `content/paths/authorization__post_oauth2_token--refresh.yml` I'm seeing $ref's pointing to `#/components`, but there is no `components` inside that file. I think it's trying to get back up to the main `components` in the openapi.yml which is not valid. Basically the # means "this file", so you'd need to $ref to "../openapi.yml#/components/schemas/foo"  for that.

Exposing this much into the file system makes it feel brittle I know, but thankfully OpenAPI 3.1 has moved on to supporting $id's for bundling, which is a whole lot nicer. https://apisyouwonthate.com/blog/openapi-v3-1-and-json-schema

Anyhow, I bring this all up because doing invalid things will restrict your ability to use the widest variety of tooling, and leave you stuck on tools which happen to support your way of doing things. I know some do, but might be better to get to being valid OpenAPI all the same.

Or, if you think OpenAPI should change to support the way you use $ref, perhaps you could join one of the https://lists.openapis.org/g/tsc/calendar calls to raise the topic? We love participation and it makes the spec better for everyone!

**Comment by Smartoneinok** [comment]
Hi - based on how the entire site (developer.box.com) is architected and built, what you are seeing is expected. We may plan a site rework in the future but are not planning to at this time.

**Comment by philsturgeon** [comment]
Can I offer some assistance? Using your own personal+invalid flavour of OpenAPI is not useful for other users, so if that’s the case maybe just make this repo private to avoid any confusion?
