### ISSUE TITLE
Documentation of various types inconsistent with example responses

### ISSUE THREAD

**Issue by lucastheisen** [box/box-openapi#242]
## Description of the issue

Currently the documentation for [File (base)](https://developer.box.com/reference/resources/file--base/) says `id` has type `string`, but the example json shows numeric:

```json
{
  "id": 12345,
  "type": "file",
  "etag": 1,
}
```

The [actual openapi definition also says `string`](https://github.com/box/box-openapi/blob/main/content/responses/file--base.yml#L23). The same stands for `etag` and other fields throughout the documentation on various types (but have not done a thorough inspection of all the examples).

I am _not_ a Boxer (assuming that means employee of Box).

I would provide a PR if i knew which direction the fix should go in.  I imagine its the _example_ that is wrong because the API currently responds with numeric values, but cannot be certain.

## Current content

```json
{
  "id": 12345,
  "type": "file",
  "etag": 1,
}
```
## Expected content

```json
{
  "id": "12345",
  "type": "file",
  "etag": "1",
}
```

**Comment by lucastheisen** [comment]
Additionally, I notice that the Users object says `notification_email` is an object, but the response i am getting is an array.

**Comment by bszwarc** [comment]
@lucastheisen - sorry for coming back to you with a delay - we are aware and working on this issue.

**Comment by bszwarc** [comment]
This has been fixed - strings are displayed properly.
