### ISSUE TITLE
fields (comma seperated list) is a string not an array of string

### ISSUE THREAD

**Issue by mhagmajer** [box/box-openapi#286]
The following attributes have wrongly defined `schema`:

https://github.com/box/box-openapi/blob/fddf0255da628a11818733eb68a920384ea3ae5c/content/attributes/fields.yml#L17
https://github.com/box/box-openapi/blob/fddf0255da628a11818733eb68a920384ea3ae5c/content/attributes/fields--with_metadata.yml#L22

**Comment by bszwarc** [comment]
Already done.
