### ISSUE TITLE
file_extensions is a string not an array of strings

### ISSUE THREAD

**Issue by mhagmajer** [box/box-openapi#287]
https://github.com/box/box-openapi/blob/900dacfb99df0c4c8a48c97db7cbcc2b0f580b3e/content/paths/search__get_search.yml#L82

**Comment by mhagmajer** [comment]
Same for `created_at_range`, `updated_at_range`, `owner_user_ids`, `recent_updater_user_ids`, `ancestor_folder_ids`

**Comment by mhagmajer** [comment]
And `size_range`

**Comment by mhagmajer** [comment]
And `content_type` (string not an array of literals)

**Comment by mhagmajer** [comment]
Same for `mdfilters` - the spec should somehow specify that the input object needs to be serialized in a comma separated list - we can't just pass an object to the query param which is always string

**Comment by bszwarc** [comment]
Fixed
