### ISSUE TITLE
fields example has a spelling mistake

### ISSUE THREAD

**Issue by mitquinn** [box/box-openapi#402]
### Description of the issue

field should be fields

### Current content

?field=metadata.enterprise_12345.contractTemplate

### Expected content

?fields=metadata.enterprise_12345.contractTemplate

### Link to the documentation page

https://developer.box.com/reference/get-folders-id-items/#param-fields

**Comment by wsocha** [comment]
Hey @mitquinn, thank you for finding this error. We fixed it.
