### ISSUE TITLE
Upload-openapi definition contains invalid 'required' property

### ISSUE THREAD

**Issue by MikeRalphson** [box/box-openapi#7]
https://github.com/box/box-openapi/blob/master/v2.0/upload.openapi-v2.json#L1194

```json
"required": "true"
```

should be

```json
"required": true
```

Happy to submit a PR if the process is simply to amend the file.

**Comment by KarthikShanmugasundaram** [comment]
@MikeRalphson please submit a PR. Thanks for contributing.

**Comment by KarthikShanmugasundaram** [comment]
Merged the pull request
