### ISSUE TITLE
Reformat Metadata Query results to return files/folders with metadata as field on items

### ISSUE THREAD

**Issue by akhor93** [box/box-openapi#95]
The Box Metadata team is changing the response to the query api. We're combining metadata and the associated item and switching the item from Standard to Mini. Design (must be Box account): https://docs.google.com/document/d/1aIvZeOiTJggjuV3V1m_kUp-oUd5ZNhjLkjU51X7Gvog/edit?usp=sharing

**Comment by cbetta** [comment]
Closed by #99
