### ISSUE TITLE
Inconsistent response content schema in `post_legal_hold_policies`

### ISSUE THREAD

**Issue by yusuf-musleh** [box/box-openapi#98]
Hello, I found the following in the OpenAPI spec for the response code `400` of the `post_legal_hold_policies` path:

```
"400": {
  "description": "Returns an error if required parameters are missing,\nor neither `is_ongoing` or filter dates are specified.",
  "content": {
    "application/json": {
      "schema": {
        "$ref": "#/components/schemas/LegalHoldPolicy"
      }
    }
  }
}
```
It seems like it should be `"$ref": "#/components/schemas/ClientError"` instead in https://github.com/box/box-openapi/blob/fe20b0e38eedfb8529bf9afd42972aca916e008a/content/paths/legal_hold_policies__post_legal_hold_policies.yml#L101

**Comment by cbetta** [comment]
@yusuf-musleh thank you for notifying us, it should be indeed. I've fixed it now.
